### ISSUE TITLE
Crash when using UIAppearence

### ISSUE THREAD

**Issue by igorkulman** [BeauNouvelle/SimpleCheckbox#14]
When trying to style the control using UIAppearence I get a crash

```
"Thread 1: EXC_BAD_ACCESS" error 
```

accessing basically any property, for example

```
Checkbox.appearance().borderStyle = .circle
```

**Comment by BeauNouvelle** [comment]
Thanks. I'll check it out!

**Comment by allo86** [comment]
As today, this is still crashing

**Comment by BeauNouvelle** [comment]
Will revisit thank you. I'll try and get this working with a bunch of different appearance settings.

**Comment by igorkulman** [comment]
I have this fixed in my fork, just waiting for Hacktoberfest to start 😉
