### ISSUE TITLE
checkbox with label

### ISSUE THREAD

**Issue by king804** [BeauNouvelle/SimpleCheckbox#15]
i am learning to swift, when the checkbox with label to same line, how to set click function for label and then checkbox selected?

thanks!

**Comment by BeauNouvelle** [comment]
I think I understand what you're asking.

```
[ ] My Label
|^^^^^^^^^^^^|
        Tap anywhere in this area and the checkbox is ticked.
```

1. You can change your label to a button and use the event trigged by that touch to set the checkbox to a checked state.

2. Add a touch gesture recognizer to your label and use the event triggered by the gesture recognizer to set the checkbox to a checked state.
