### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by lazar89nis** [BeauNouvelle/SimpleCheckbox#20]
Why did you remove CocoaPod?

**Comment by Sunitadaffodil** [comment]
Any plan of CocoaPod support?

**Comment by jaredcowoCS** [comment]
Do you plan to add support for CocoaPod?

**Comment by jaredcowoCS** [comment]
pod 'SimpleCheckbox'
Just add this to your pod file and it should work.

**Comment by BeauNouvelle** [comment]
I'll add it back in, along with Swift Package Manager support.

**Comment by BeauNouvelle** [comment]
The email I have registered with the pod doesn't exist anymore, so I'm unable to create a session to push changes to the podspec. I've contacted the cocoa pod team a few times now, with no replies. So for now, no cocoa pods.
