### ISSUE TITLE
Use in SwiftUI

### ISSUE THREAD

**Issue by knightpop** [BeauNouvelle/SimpleCheckbox#23]
Hello, I want to use this library in SwiftUI.

How can I use this?
```
var body: some View {
  HStack {
    Checkbox(frame: CGRect(x: 50, y: 50, width: 25, height: 25))
    Text("HelloWorld!")

  }
}
```

Like this.

Sorry, I'm a newbie in SwiftUI and IOS also.

**Comment by BeauNouvelle** [comment]
This is a UIKit only project unfortunately, however I may port it over to SwiftUI in the future.
