### ISSUE TITLE
How to call the listener programmatically?

### ISSUE THREAD

**Issue by R-Ashh** [BeauNouvelle/SimpleCheckbox#24]
Hi, first I wanted to thank you for your library, then I wanted to ask you what is the way to call the change value function and call the listener after, for example by clicking on a label I wanna trigger the checkbox and listener, is there any way to do that?  thanks in advance

**Comment by BeauNouvelle** [comment]
You can add a touch gesture or override the touchesBegan function of your label and use that to set the value for the checkbox.
