### ISSUE TITLE
Make class open

### ISSUE THREAD

**Issue by smamczak** [BeauNouvelle/SimpleCheckbox#27]
Hi, would it be possible to make the class `open` instead of `public`? thanks

**Comment by BeauNouvelle** [comment]
No problem. You could do a PR if you like? Hacktoberfest is coming up. Perfect opportunity to get yourself a free t-shirt!
https://hacktoberfest.digitalocean.com

**Comment by smamczak** [comment]
Hi, I've created a PR #30

**Comment by BeauNouvelle** [comment]
Thank you! I have some time tomorrow. Will review and merge!
