### ISSUE TITLE
'@objc' enum raw type 'String' is not an integer type

### ISSUE THREAD

**Issue by smamczak** [BeauNouvelle/SimpleCheckbox#32]
Hi, I downloaded the new version and I have this errors

![Zrzut ekranu 2020-10-20 o 00 03 18](https://user-images.githubusercontent.com/17873294/96516577-b73b9980-1267-11eb-9924-46b0059f921c.png)

**Comment by OlivierGuy13** [comment]
I have download the 2.2.0 version via SPM and I have the same error :(

**Comment by rhys-at-speer** [comment]
@smamczak @OlivierGuy13 Changing `String` to `Int` on lines 17, 32, 45, and 60 seems to work

**Comment by r-ba** [comment]
@smamczak @OlivierGuy13 Changing `String` to `Int` on lines 17, 32, 45, and 60 seems to work

**Comment by smamczak** [comment]
@r-ba @OlivierGuy13 Yes, but the point of this change is that is should me in the offical repo @BeauNouvelle

**Comment by r-ba** [comment]
@smamczak I'm sure @BeauNouvelle would be happy to merge a PR

**Comment by BeauNouvelle** [comment]
Happy to review!

**Comment by takasurazeem** [comment]
Is it fixed guys? What version should I be pointing to?

**Comment by smamczak** [comment]
@takasurazeem there was no release since 2.2.0. Changes are only on master.
@BeauNouvelle could you please tag latest commit with new version? Thanks

**Comment by BeauNouvelle** [comment]
Just done. 2.2.1 Please let me know if you have any further troubles with it!

**Comment by smamczak** [comment]
Works great. Thanks!

**Comment by takasurazeem** [comment]
> Just done. 2.2.1 Please let me know if you have any further troubles with it!

I'll try, there was a tvOS error as well `'UIImpactFeedbackGenerator' is unavailable in tvOS`. I'll check to see if it occurs again or not.
