### ISSUE TITLE
Will not work with Xcode 15

### ISSUE THREAD

**Issue by doodahdayz** [BeauNouvelle/SimpleCheckbox#38]
Trying to compile a project that uses this Swift Package results in error.  Not useable with Xcode 15 as of now.

/SourcePackages/checkouts/SimpleCheckbox/checkbox/Checkbox.swift:104:6 Stored properties cannot be marked unavailable with '@available'

Line 104 in the Checkbox class.

**Comment by BeauNouvelle** [comment]
Interesting. Thank you I'll get this fixed.

**Comment by doodahdayz** [comment]
Easy fix… one of the directives won’t compile when using the package….

**Comment by BeauNouvelle** [comment]
I removed it. It's not even in use anymore, so it's gone. Thanks for this!

**Comment by doodahdayz** [comment]
Thank you! It’s a lovely Swift Package.
