### ISSUE TITLE
Cannot override with a stored property 'borderWidth'

### ISSUE THREAD

**Issue by bbookman** [BeauNouvelle/SimpleCheckbox#7]
I get the compiler error 

> Cannot override with a stored property 'borderWidth' Overriding non-open var outside of its defining module

on this line

`public var borderWidth: CGFloat = 2`

P.S. Love this repo and thanks!

**Comment by BeauNouvelle** [comment]
Hi there. I'm glad you like it!

It looks like what you're trying to do isn't possible. 
https://stackoverflow.com/a/24094339/2114482

The workaround for this is to set the `borderWidth` inside the initializer.

```
class MyCheckbox: Checkbox {

    override init(frame: CGRect) {
        super.init(frame: frame)
        borderWidth = 2
    }

    public required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}
```

**Comment by bbookman** [comment]
The code is **your code** not mine :) . Sorry, I should have been more clear

In your Checkbox.swift file...
`60 | public var borderWidth: CGFloat = 2`

**Comment by bbookman** [comment]
to fix this, i simply commented out that line and everything works.
