### ISSUE TITLE
Dependency "SimpleCheckbox" has no shared framework schemes

### ISSUE THREAD

**Issue by Kitty555** [BeauNouvelle/SimpleCheckbox#9]
Vivids-Mac:test vivid$ carthage update
*** Fetching SimpleCheckbox
*** Checking out SimpleCheckbox at "1.4.0"
*** xcodebuild output can be found in /var/folders/60/lghfh6v13kvbfbjh538qhlf00000gn/T/carthage-xcodebuild.8Bnp8R.log
*** Skipped building SimpleCheckbox due to the error:
Dependency "SimpleCheckbox" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/BeauNouvelle/SimpleCheckbox/issues/new

I don't know why this error have. please help me. 
Thanks.

**Comment by BeauNouvelle** [comment]
Sorry for this being a little late, but I have now resolved this issue.
